#!/bin/sh
# Install native apps

# Homebrew Cask
brew install caskroom/cask/brew-cask

# Symlink to Main Applications Directory
export HOMEBREW_CASK_OPTS="--appdir=/Applications";

# Programs
brew cask install google-chrome 2> /dev/null
brew cask install caffeine 2> /dev/null
brew cask install torbrowser 2> /dev/null
brew cask install istat-menus 2> /dev/null
brew cask install google-backup-and-sync 2> /dev/null
brew cask install sketch 2> /dev/null
brew cask install atom 2> /dev/null
brew cask install duet 2> /dev/null
brew cask install appzapper 2> /dev/null
brew cask install 1password 2> /dev/null
brew cask install gpgtools 2> /dev/null
brew cask install sonos 2> /dev/null
brew cask install adobe-creative-cloud 2> /dev/null
brew cask install arq 2> /dev/null
brew cask install toggl 2> /dev/null 

# Fonts
brew cask install font-inconsolata 2> /dev/null
brew cask install font-source-code-pro 2> /dev/null
brew cask install font-roboto 2> /dev/null

# Wrap it up
brew cask cleanup
