#!/bin/sh
# Install native apps

# Homebrew Cask
brew install caskroom/cask/brew-cask

# Symlink to Main Applications Directory
export HOMEBREW_CASK_OPTS="--appdir=/Applications";

# Programs
brew cask install google-chrome 2> /dev/null
brew cask install google-chrome-canary 2> /dev/null
brew cask install caffeine 2> /dev/null
brew cask install torbrowser 2> /dev/null
brew cask install istat-menus 2> /dev/null
brew cask install flux 2> /dev/null
brew cask install google-drive 2> /dev/null
brew cask install sketch 2> /dev/null
brew cask install sublime-text 2> /dev/null

# Fonts
brew cask install font-inconsolata 2> /dev/null
brew cask install font-source-code-pro 2> /dev/null
brew cask install font-roboto 2> /dev/null

# Wrap it up
brew cask cleanup
