#!/bin/sh
# Install native apps

# Homebrew Cask
brew install caskroom/cask/brew-cask

# Symlink to Main Applications Directory
export HOMEBREW_CASK_OPTS="--appdir=/Applications";

# Programs
brew cask install google-chrome 2> /dev/null
brew cask install google-chrome-canary 2> /dev/null
brew cask install torbrowser 2> /dev/null
brew cask install iterm2 2> /dev/null
brew cask install virtualbox 2> /dev/null
brew cask install vlc 2> /dev/null
brew cask install alfred 2> /dev/null
brew cask install appzapper 2> /dev/null
brew cask install transmission 2> /dev/null
brew cask install istat-menus 2> /dev/null
brew cask install gpgtools 2> /dev/null
brew cask install the-unarchiver 2> /dev/null
brew cask install flux 2> /dev/null
brew cask install google-drive 2> /dev/null
brew cask install sketch 2> /dev/null
brew cask install sketch-toolbox 2> /dev/null
brew cask install vagrant 2> /dev/null
brew cask install dash 2> /dev/null
brew cask install sublime-text3 2> /dev/null
brew cask install atom-mac 2> /dev/null
brew cask install monotype-skyfonts 2> /dev/null
brew cask install sophos-anti-virus-home-edition 2> /dev/null

# Fonts
brew cask install font-inconsolata 2> /dev/null
brew cask install font-source-code-pro 2> /dev/null

# Wrap it up
brew cask cleanup
